# Generated by Django 4.1.2 on 2022-10-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
